---
 - name: OS update is in progress for RedHat 7 or RedHat 6
   yum:
     name: '*'
     state: latest
     security: "{{ sec_update }}"
     exclude: "{{ exclude_package }}"
   when: 
       - ansible_distribution == "RedHat"
       - ansible_distribution_major_version|int >= 6

 - name: OS update is in progress for RedHat 8
   dnf:
     name: '*'
     state: latest
     security: "{{ sec_update }}"
     exclude: "{{ exclude_package }}"
   when: 
       - ansible_distribution == "RedHat" 
       - ansible_distribution_major_version == "8"
    
 - name: yum-clean-metadata
   ansible.builtin.command: yum clean metadata

 - name: Check for reboot hint.
   command: needs-restarting -r
   no_log: true
   register: reboot_hint
   failed_when: reboot_hint.rc >= 2

 - name: Rebooting ...
   shell: sleep 2 && /sbin/shutdown -r now "Reboot required for updated kernel"
   async: 1
   poll: 0
   ignore_errors: true
   when: reboot_hint.rc == 1
   register: rebooting

 - name: Wait for system to become reachable
   wait_for_connection:
     timeout: 900
     sleep: 15
     delay: 30
   when: rebooting.changed
