---

  - name: get host virtulazation state
    ansible.builtin.setup:
      filter: 
        - "ansible_system_vendor"
        - "ansible_hostname"
        - "ansible_virtualization_role"
        - "ansible_distribution"
        - "ansible_distribution_major_version"
    register: sonuc
    ignore_unreachable: true

  - name: workspace global variable VM
    set_stats:
      data: 
        guest_name: ["{{ item }}",]
    when: sonuc.ansible_facts.ansible_system_vendor == "VMware, Inc."
    with_items: "{{ vm_name }}"
    ignore_errors: true

  - name: Add ReaR backup conf.
    copy:
      src: templates/rear.conf.j2
      dest: /etc/rear/local.conf
      mode: '0600'
      owner: root
      group: root
      backup: yes
    when: sonuc.ansible_facts.ansible_virtualization_role == "host"

  - name: Manual run backup
    shell: /usr/sbin/rear -d -v mkbackup
    when: sonuc.ansible_facts.ansible_virtualization_role == "host"
