---
- name: "Sending mail for Failed hosts"
  mail:
    host: relay.abc.com.tr
    port: 587
    from: awx@abc.com.tr
    to: "{{ admin }}"
    cc: "{{ admin }}"
    subject: " Patch Failed Raporu - {{ ansible_date_time.date }} - {{ ansible_date_time.time }}"
    body: "{{ lookup('template','templates/failed_server_mail.html.j2') }}"
    subtype: html
    charset: utf8
  run_once: true
  delegate_to: localhost
  ignore_errors: true

- name: "Print execution results"
  debug:
    msg: "{{ item }}"
  with_items: "{{ register_failed }}"
 